import {
  siAndroid,
  siApachejmeter,
  siApachemaven,
  siAppium,
  siApple,
  siBitbucket,
  siDocker,
  siGit,
  siGithub,
  siGithubactions,
  siJenkins,
  siJira,
  siJunit5,
  siOllama,
  siOpenjdk,
  siPandas,
  siPython,
  siSelenium,
  siTypescript,
  type SimpleIcon,
} from "simple-icons";

export const techIcons: Record<string, SimpleIcon> = {
  android: siAndroid,
  apachejmeter: siApachejmeter,
  apachemaven: siApachemaven,
  appium: siAppium,
  apple: siApple,
  bitbucket: siBitbucket,
  docker: siDocker,
  git: siGit,
  github: siGithub,
  githubactions: siGithubactions,
  jenkins: siJenkins,
  jira: siJira,
  junit5: siJunit5,
  ollama: siOllama,
  openjdk: siOpenjdk,
  pandas: siPandas,
  python: siPython,
  selenium: siSelenium,
  typescript: siTypescript,
};
